version: "3.8"

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:1.4.0
    container_name: tgi-cpu
    ports:
      - "8080:80"
    environment:
      MODEL_ID: TinyLlama/TinyLlama-1.1B-Chat-v1.0
      MAX_INPUT_LENGTH: 1024
      MAX_TOTAL_TOKENS: 1536
      NUM_SHARD: 1
